spring:
  application:
    name: bendito-percal
  datasource:
    url: jdbc:postgresql://localhost:5432/bendito_percal
    username: bendito_percal
    password: bendito_percal
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    locations: classpath:db/migration

app:
  dashboard:
    timezone: ${DASHBOARD_TIMEZONE:America/Fortaleza}
